### ISSUE TITLE
tigeringarden to-do (today and tomorrow)

### ISSUE THREAD

**Issue by ghost** [andrewniekamp/seattle_health_clinic#2]
- [x] index.cshtml with working connections to JS/CSS
- [x] design landing/sign-in page (will need to watch/read some tutorials)
- [x] create layout page template for views
- [x] create view pages and ensure proper functioning
- [x] routing for forms

**misc**
- [ ] switch from bootstrap and jquery CDNs to files
- [x] center landing page panel
- [ ] signout should create a modal window
- [x] organize views
- [x] list groups in individual views should have active tag change depending on what is clicked

**bug**
- [ ] SQLDataReader in VerifyLogin creates empty records

**remaining features**
- [x] current employees page
- [x] individual page view for roster
- [x] home view
- [x] add new employee page
- [x] edit new employee page
- [x] sort for information on roster page
- [x] employer actions panel in individual employee page

**Comment by ghost** [comment]
**Notes**
- Content Accordion: https://teamtreehouse.com/library/create-an-accordion-menu-with-css
- Flex Box Example: http://codepen.io/nickpettit/pen/KtcyI
- Create Modal Window CSS: https://teamtreehouse.com/library/create-a-modal-window-with-css
  http://codepen.io/davidicus/pen/ZYjoVO

**Comment by yichiang** [comment]
Patient
-Critical patients
-View current patients
-Add new patient
